### ISSUE TITLE
Error while connecting to Alluxio client through Python

### ISSUE THREAD

**Issue by alokgogate** [Alluxio/alluxio-py#1]
I get the error "No JSON object could be decoded" when I do the following steps 
import alluxio
from alluxio import option
client = alluxio.client(hostname, port)
root_stats = client.list_status('/')
for stat in root_stats:
    print pretty_json(stat.json())

This is as per the python client documentation

**Comment by aaudiber** [comment]
Hi @alokgogate,

Are there any errors or warnings in `proxy.log`, `master.log`, or `worker.log` under `${ALLUXIO_HOME}/logs/`? Can you run `jps` to make sure the `AlluxioMaster`, `AlluxioWorker`, and `AlluxioProxy` services are all running?

@uronce-cc, do you know common causes for this error message?

**Comment by uronce-cc** [comment]
@alokgogate https://github.com/Alluxio/alluxio-py/blob/master/example.py#L68

`stat` is a `alluxio.wire.FileInfo` object, it needs to call `stat.json()` to return an encoded json string for the object, then pass `stat.json()` to `pretty_json`.

**Comment by uronce-cc** [comment]
@aaudiber @alokgogate I cannot reproduce, @alokgogate are you sure you called `stat.json()`, if you call `pretty_json(stat)`, then the error is expected. Could you share the result of `print stat`?

**Comment by uronce-cc** [comment]
@alokgogate is the issue resolved?
