### ISSUE TITLE
In case of TLS encryption enabled on Alluxio server, can I connect to it using an application built on top of this python library?

### ISSUE THREAD

**Issue by thewarpup** [Alluxio/alluxio-py#11]

**Comment by pedersen** [comment]
Under the covers, this library uses [requests](https://requests.readthedocs.io/en/master/) to connect to the Alluxio proxy server, so to some degree, the answer is likely to be yes.

If you are asking if this library provides a mechanism for you to specify a TLS cert to authenticate against the Alluxio proxy server, then no, it does not. You may be able to achieve similar your results using environment variables and the requests library, but I'm not sure. I've never tried that.
