### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by reiz** [Alluxio/alluxio-py#20]
Under which license is this code published? 
I checked out the license.txt file but could not really recognise a license. Just a bunch of XML tags.

**Comment by Xenorith** [comment]
i took a random stab and searched for `apache`, which showed this snippet in the license.txt
```
 <p class="text-small text-gray mb-0 lh-condensed-ultra">
      Alluxio/alluxio-go is licensed under the
    </p>
    <h4 class="mt-0 mb-2">Apache License 2.0</h4>
    <p class="mb-0 text-gray text-small pr-2">A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.</p>
```

**Comment by reiz** [comment]
@Xenorith Thanks!

**Comment by apc999** [comment]
@reiz  thanks for reporting this issue. it should be under Apache License 2.0 like Alluxio/alluxio main repo. We will update this repo shortly.
