### ISSUE TITLE
Issue in REST API endpoints on server

### ISSUE THREAD

**Issue by AbdurRehman91** [Alluxio/alluxio-py#4]
i am using https://alluxio-py.readthedocs.io. When configuring and running locally it works fine.I can explain with a  example.When creating the folder through the api locally,its working fine.But when i tried to create directory through REST API on the server ,it does not work accordingly .The generated path url on the server gives me HTTP error 404. Also the rest api document does not provide with a sample url https://docs.alluxio.io/os/restdoc/stable/master/index.html#-1568692663

**Comment by AbdurRehman91** [comment]
Can any one provide any update on this ?

**Comment by ZacBlanco** [comment]
Hi @AbdurRehman91 sorry for the late response! If you post your issue on the Alluxio repository (https://github.com/Alluxio/alluxio) it will likely get more visibility.

Regarding your issue, Are you saying that when deploying in a non-local environment when you try creating a directory it fails. Is this the case? If you can provide a code sample to reproduce it would help us.

Thanks!

**Comment by apc999** [comment]
Closing this issue as it should be opened at (https://github.com/Alluxio/alluxio)
