### ISSUE TITLE
Update alluxio python client on pypi.org,

### ISSUE THREAD

**Issue by soliverr** [Alluxio/alluxio-py#5]
Hi.

What about updating alluxio python client on pypi.org, may be with version 0.1.2? It seems last commit 
https://github.com/Alluxio/alluxio-py/commit/00137ad71ac2638e227e5e43200e84ba068982aa (Be compatible with Python3) is not included in module distribution.

**Comment by apc999** [comment]
@LuQQiu  can you check if cherrypicking the commit helps? thanks
