### ISSUE TITLE
Setup.py Installation Bug

### ISSUE THREAD

**Issue by pedersen** [Alluxio/alluxio-py#8]
I've submitted a PR for this issue at https://github.com/Alluxio/alluxio-py/pull/7

We can't add alluxio-py to any requirements.txt because of the way that the modules are structured. I've done a minimally intrusive update to setup.py to keep the __version__ string where it is and allow setup.py to find it. If we could merge this, and do a new release, it would help out everybody who uses Alluxio and Python.

**Comment by ZacBlanco** [comment]
@pedersen / @apc999 Since the PR is merged this can be closed now

**Comment by apc999** [comment]
closed by https://github.com/Alluxio/alluxio-py/issues/7
